### PR TITLE
Update Readme, with heimdall and badge fixes

### PR DESCRIPTION
**Pull request by firfircelik**
according to #93

### CODE REVIEW

**Comment by kcajmagic** [comment]
@firfircelik thank you for doing these changes. Can you please sign the CLA so I can merge in this PR.

**Comment by firfircelik** [comment]
@kcajmagic done

**Comment by kcajmagic** [comment]
@firfircelik, sorry for the inconvenience it appears that the commits were made are not attached to your github account. 

I believe you need to attach your github email to your [git config](https://help.github.com/en/articles/setting-your-commit-email-address)

**Comment by kristinaspring** [comment]
@firfircelik, Do you need any guidance with how to re-commit your changes with your config set to the correct user.name and user.email?  Anything we can help with to get this merged?

**Comment by firfircelik** [comment]
according to conversation https://github.com/xmidt-org/codex-deploy/issues/95#issuecomment-546841800  I'm passing this issue.

since I done all needed for CLA and result is still same.

**Comment by kristinaspring** [comment]
The commits you made (here is one: https://github.com/xmidt-org/codex-deploy/pull/99/commits/552aeaa31e60aa3df25be25aa8d49f60973eb59c, you can see it says your username has committed it but the icon is wrong) are not attached to your account.  Even though you signed the CLA, the commits themselves are perceived as from a "different user".  The most common reason for that is that your email is not attached to your git configuration, so the commits don't have your email in them.  That is what Jack was telling you 17 days ago and we tried to help you with.

Since you have given the issue to someone else to fix, I am closing this pull request.

**Pull request closed without merging**
